"""empty message

Revision ID: 6e18ac6fedec
Revises: 90668ede7cc7
Create Date: 2019-05-30 16:33:22.150756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e18ac6fedec'
down_revision = '90668ede7cc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment='昵称',
               existing_comment='用户名',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=mysql.VARCHAR(length=64),
               comment='用户名',
               existing_comment='昵称',
               existing_nullable=False)
    # ### end Alembic commands ###
