"""xx

Revision ID: 90668ede7cc7
Revises: 
Create Date: 2019-05-30 16:07:12.790297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90668ede7cc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('nickname', sa.String(length=64), nullable=False, comment='用户名'),
    sa.Column('mobile', sa.String(length=16), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=64), nullable=False, comment='邮箱'),
    sa.Column('sex', sa.Boolean(), nullable=False, comment='性别: 女(0)/男(1)'),
    sa.Column('avatar', sa.String(length=64), nullable=False, comment='头像'),
    sa.Column('username', sa.String(length=32), nullable=False, comment='登录账号'),
    sa.Column('password', sa.String(length=32), nullable=False, comment='登录密码'),
    sa.Column('salt', sa.String(length=32), nullable=False, comment='盐'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='账户状态: 无效(0)/有效(1)'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='账号创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='最后一次登录时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
